#!/usr/bin/env bash

# script that configures a new Ubuntu machine torespect above
#   requirements installs nginx on a webserver

apt get update
apt get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee -i /var/www/html/index.html
service nginx restart
