#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirement

sudo apt-get -y update 
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
