#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirement

apt-get updat -y
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
