#!/usr/bin/env bash
# configures Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
#string="server_name_;\n\trewrite^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4@;"
#sudo sed -i s/"server_name_;/$string"/g /etc/nginx/sites-enabled/default:
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
