#!/usr/bin/env bash

# configures Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
#string="server_name_;\n\trewrite^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4@;"
#sudo sed -i s/"server_name_;/$string"/g /etc/nginx/sites-enabled/default

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
new_string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx start
