#!/usr/bin/env bash

# configures Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
sudo apt update
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
string="server_name_;\n\trewrite^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sudo sed -i s/"server_name_;/$string"/g /etc/nginx/sites-enabled/default
sudo service nginx restart
