#!/usr/bin/env bash
# script that installs load balance

sudo apt-get -y update
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install haproxy=2.0.\*
loadbalancer=\ 
"frontend http
  bind *:80
  mode http
  default_backend web-backend

backend web-backend
   balance roundrobin
   server 63064-web-01 52.91.124.211:80 check
   server 63064-web-02 54.210.105.136:80 check" 
echo "$loadbalancer" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
