#!/usr/bin/env bash
# script that installs load balance

sudo apt-get -y updatei
sudo apt-get -y install nginx
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install haproxy=2.0.\*
loadbalancer =\ 
"frontend http
  bind *:80
  mode http
  default_backend web-backend

backend web-backend
   balance roundrobin
   server 63064-web-01 52.91.124.211:80 check
   server 63064-web-02 54.210.105.136:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
