#!/usr/bin/env bash
# Bash script that displays Best School 10 times.

i=1

while [ $i -lt "10" ]
do
    echo "Best School"

    if [ $i -eq "9" ]
    then
        echo "Hi"
        echo "Best School"
    fi

    ((i += 1))
done
