#!/usr/bin/env bash
#Script that displays Best School 10 times,
#+but for the 9th iteration displays Hi

i=1
while [ $i -le 10 ];
do
	if [ $i -eq 9 ];
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
