#!/usr/bin/env bash
#Script that gives you information about 
#+ the school file

fileName=school
if [ -e "$fileName" ];
then
	echo "school file exists"
	if [ -s "$fileName" ]; then
		echo "school file is empty"
	else
		echo "$fileName file is empty"
	fi

	if [ -f $fileName ]; then
		echo "$fileName is a regular file"
	fi
else
	echo "school file does not exist"
fi
